### ISSUE TITLE
Not handling From

### ISSUE THREAD

**Issue by dceejay** [mat-sz/microMTA#1]
Hi,

for some reason I have an email client that sends  `MAIL From:<joe@foo.com>`   rather than MAIL FROM:... 
which causes you to reject it... - This may be correct spec wise but it would nice if you could handle it...

line 414 of connection.js could be args[0].toUpperCase().startsWith('FROM:<') &&   
ie add the .toUpperCase()

likewise like 450 just in case the TO parameter is also To

I notice you do do it on line 421 for SIZE so hopefully this isn't too much of an ask.

Thanks

**Comment by mat-sz** [comment]
@dceejay For some reason I have not noticed this issue.

I've fixed the issue and published version 1.1.1 with the patch.
